### ISSUE TITLE
Question about  information_of_time file

### ISSUE THREAD

**Issue by diewufeihong** [MoonLight-SteinsGate/EcoFuzz#1]
Hello, I tried using Ecofuzz to test gif2png for about 18 hours, and the output contains the  information_of_time file. Its size is about 20G. I'm not sure why it happened, could you please help to check the reason? In addition, for the test of gif2png, I randomly downloaded 9 gif files from the Internet as initial seeds.

**Comment by MoonLight-SteinsGate** [comment]
The information_of_time file and other similar files are used to track the detailed information during testing. EcoFuzz will write the time interval of each turn of fuzzing into the information_of_time file if EcoFuzz finishes fuzzing one selected seed. Generally, we test some programs such as objdump for 100+ days. The size of information file generated by EcoFuzz is no more than 100M. Therefore, your situation is really rare. I suggest you modifying the source code to abolish the track mechanism.

**Comment by diewufeihong** [comment]
Okay,I see. Thanks.
