### ISSUE TITLE
restore deterministic strategies

### ISSUE THREAD

**Issue by ricardo-kcc** [MoonLight-SteinsGate/EcoFuzz#2]
1. Ecofuzz runs without the deterministic strategies. what should I do if I want to restore the deterministic stage ? I think the deterministic stage is helpful for mutation, such as eff_map.
2. I don't understand what the function ` calculate_power` does  when I try to restore the deterministic stage.
https://github.com/MoonLight-SteinsGate/EcoFuzz/blob/1fd94608291b708e9c97240780aea16349c688b8/EcoFuzz/afl-fuzz.c#L5341
Thanks!

**Comment by MoonLight-SteinsGate** [comment]
According to our design, the energy allocated to each seed by EcoFuzz determines the number of test cases generated by the seed. If the energy is less than the power needed in the deterministic strategies, which is calculated by `calculate_power(len)`, the deterministic strategies will be not implemented.

**Comment by ricardo-kcc** [comment]
Thanks.
